### ISSUE TITLE
Request - availability of notebook for the 2D GWL contour maps

### ISSUE THREAD

**Issue by pirao** [marcohmer/GMNO#1]
Since the 1D case is already in the repository, are there any plans on also providing the other notebooks used in your study like the 2D optimal sensor location notebook?

**Comment by marcohmer** [comment]
Hello Arthur,
Yes, it is planned to upload the 2D optimization as well. Originally both should be on GitHub at the same time, but unfortunately, the data size of the interpolated GW contour maps was too big. Therefore I will create a smaller dummy dataset soon and upload it during August (I am currently working on my doctoral defense and have no time before that). I will keep you posted.

Cheers Marc

Von: Arthur Cancellieri Pires ***@***.***>
Gesendet: Samstag, 23. Juli 2022 14:46
An: marcohmer/GMNO ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [marcohmer/GMNO] Request - availability of notebook for the 2D GWL contour maps (Issue #1)


Since the 1D case is already in the repository, are there any plans on also providing the other notebooks used in your study like the 2D optimal sensor location notebook?

**Comment by pirao** [comment]
Thank you for the fast reply and good luck with your defense!
